In [4]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("MobilePriceRange.csv")
df.head()

,BatteryPower,InternalMemory,ClockSpeed,NoOfCores,RAM,TalkTime,DualSim,3G,4G,WiFi,...,MobileDepth,MobileWeight,TouchScreen,ScreenHeight,ScreenWidth,FrontCameraPx,RearCameraPX,PxHeight,PxWeight,PriceRange
0,842,7,2.2,2,2549,19,0,0,0,1,...,0.6,188,0,9,7,1,2,20,756,Medium
1,1021,53,0.5,3,2631,7,1,1,1,0,...,0.7,136,1,17,3,0,6,905,1988,High
2,563,41,0.5,5,2603,9,1,1,1,0,...,0.9,145,1,11,2,2,6,1263,1716,High
3,615,10,2.5,6,2769,11,0,1,0,0,...,0.8,131,0,16,8,0,9,1216,1786,High
4,1821,44,1.2,2,1411,15,0,1,1,0,...,0.6,141,1,8,2,13,14,1208,1212,Medium

In [14]:
df.head(10)

,BatteryPower,InternalMemory,ClockSpeed,NoOfCores,RAM,TalkTime,DualSim,3G,4G,WiFi,...,MobileDepth,MobileWeight,TouchScreen,ScreenHeight,ScreenWidth,FrontCameraPx,RearCameraPX,PxHeight,PxWeight,PriceRange
0,842,7,2.2,2,2549,19,0,0,0,1,...,0.6,188,0,9,7,1,2,20,756,Medium
1,1021,53,0.5,3,2631,7,1,1,1,0,...,0.7,136,1,17,3,0,6,905,1988,High
2,563,41,0.5,5,2603,9,1,1,1,0,...,0.9,145,1,11,2,2,6,1263,1716,High
3,615,10,2.5,6,2769,11,0,1,0,0,...,0.8,131,0,16,8,0,9,1216,1786,High
4,1821,44,1.2,2,1411,15,0,1,1,0,...,0.6,141,1,8,2,13,14,1208,1212,Medium
5,1859,22,0.5,1,1067,10,1,1,0,0,...,0.7,164,0,17,1,3,7,1004,1654,Medium
6,1821,10,1.7,8,3220,18,0,1,1,1,...,0.8,139,0,13,8,4,10,381,1018,VeryHigh
7,1954,24,0.5,4,700,5,1,1,0,1,...,0.8,187,1,16,3,0,0,512,1149,Low
8,1445,53,0.5,7,1099,20,0,1,0,0,...,0.7,174,0,17,1,0,14,386,836,Low
9,509,9,0.6,5,513,12,1,1,1,0,...,0.1,93,0,19,10,2,15,1137,1224,Low

In [15]:
print("Rows and Columns:", df.shape)

Rows and Columns: (2000, 21)

In [16]:
print("Dataset Shape:", df.shape)
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Dataset Shape: (2000, 21)
Number of Rows: 2000
Number of Columns: 21

In [17]:
print(df.columns)

Index(['BatteryPower', 'InternalMemory', 'ClockSpeed', 'NoOfCores', 'RAM',
       'TalkTime', 'DualSim', '3G', '4G', 'WiFi', 'Bluetooth', 'MobileDepth',
       'MobileWeight', 'TouchScreen', 'ScreenHeight', 'ScreenWidth',
       'FrontCameraPx', 'RearCameraPX', 'PxHeight', 'PxWeight', 'PriceRange'],
      dtype='object')

In [18]:
df.columns.tolist()

['BatteryPower',
 'InternalMemory',
 'ClockSpeed',
 'NoOfCores',
 'RAM',
 'TalkTime',
 'DualSim',
 '3G',
 '4G',
 'WiFi',
 'Bluetooth',
 'MobileDepth',
 'MobileWeight',
 'TouchScreen',
 'ScreenHeight',
 'ScreenWidth',
 'FrontCameraPx',
 'RearCameraPX',
 'PxHeight',
 'PxWeight',
 'PriceRange']

In [19]:
df.dtypes

BatteryPower        int64
InternalMemory      int64
ClockSpeed        float64
NoOfCores           int64
RAM                 int64
TalkTime            int64
DualSim             int64
3G                  int64
4G                  int64
WiFi                int64
Bluetooth           int64
MobileDepth       float64
MobileWeight        int64
TouchScreen         int64
ScreenHeight        int64
ScreenWidth         int64
FrontCameraPx       int64
RearCameraPX        int64
PxHeight            int64
PxWeight            int64
PriceRange         object
dtype: object

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BatteryPower    2000 non-null   int64
 1   InternalMemory  2000 non-null   int64
 2   ClockSpeed      2000 non-null   float64
 3   NoOfCores       2000 non-null   int64
 4   RAM             2000 non-null   int64
 5   TalkTime        2000 non-null   int64
 6   DualSim         2000 non-null   int64
 7   3G              2000 non-null   int64
 8   4G              2000 non-null   int64
 9   WiFi            2000 non-null   int64
 10  Bluetooth       2000 non-null   int64
 11  MobileDepth     2000 non-null   float64
 12  MobileWeight    2000 non-null   int64
 13  TouchScreen     2000 non-null   int64
 14  ScreenHeight    2000 non-null   int64
 15  ScreenWidth     2000 non-null   int64
 16  FrontCameraPx   2000 non-null   int64
 17  RearCameraPX    2000 non-null   int64
 18  PxHeight        2000 non-null   int64
 19  PxWeight        2000 non-null   int64
 20  PriceRange      2000 non-null   object
dtypes: float64(2), int64(18), object(1)
memory usage: 328.2+ KB

In [21]:
df.isnull().sum()

BatteryPower      0
InternalMemory    0
ClockSpeed        0
NoOfCores         0
RAM               0
TalkTime          0
DualSim           0
3G                0
4G                0
WiFi              0
Bluetooth         0
MobileDepth       0
MobileWeight      0
TouchScreen       0
ScreenHeight      0
ScreenWidth       0
FrontCameraPx     0
RearCameraPX      0
PxHeight          0
PxWeight          0
PriceRange        0
dtype: int64

In [22]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 0

In [23]:
print("Target Variable:", "price_range")

Target Variable: price_range

In [25]:
for col in df.columns:
    print(col)

BatteryPower
InternalMemory
ClockSpeed
NoOfCores
RAM
TalkTime
DualSim
3G
4G
WiFi
Bluetooth
MobileDepth
MobileWeight
TouchScreen
ScreenHeight
ScreenWidth
FrontCameraPx
RearCameraPX
PxHeight
PxWeight
PriceRange

In [26]:
df["PriceRange"].head()

0    Medium
1      High
2      High
3      High
4    Medium
Name: PriceRange, dtype: object

In [27]:
df.columns = df.columns.str.strip()
print(df.columns.tolist())

['BatteryPower', 'InternalMemory', 'ClockSpeed', 'NoOfCores', 'RAM', 'TalkTime', 'DualSim', '3G', '4G', 'WiFi', 'Bluetooth', 'MobileDepth', 'MobileWeight', 'TouchScreen', 'ScreenHeight', 'ScreenWidth', 'FrontCameraPx', 'RearCameraPX', 'PxHeight', 'PxWeight', 'PriceRange']

In [30]:
print(df.columns.tolist())

['BatteryPower', 'InternalMemory', 'ClockSpeed', 'NoOfCores', 'RAM', 'TalkTime', 'DualSim', '3G', '4G', 'WiFi', 'Bluetooth', 'MobileDepth', 'MobileWeight', 'TouchScreen', 'ScreenHeight', 'ScreenWidth', 'FrontCameraPx', 'RearCameraPX', 'PxHeight', 'PxWeight', 'PriceRange']

In [31]:
df.describe()

,BatteryPower,InternalMemory,ClockSpeed,NoOfCores,RAM,TalkTime,DualSim,3G,4G,WiFi,Bluetooth,MobileDepth,MobileWeight,TouchScreen,ScreenHeight,ScreenWidth,FrontCameraPx,RearCameraPX,PxHeight,PxWeight
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,32.046500,1.522250,4.520500,2124.213000,11.011000,0.509500,0.761500,0.521500,0.507000,0.4950,0.501750,140.249000,0.503000,12.306500,5.767000,4.309500,9.916500,645.108000,1251.515500
std,439.418206,18.145715,0.816004,2.287837,1084.732044,5.463955,0.500035,0.426273,0.499662,0.500076,0.5001,0.288416,35.399655,0.500116,4.213245,4.356398,4.341444,6.064315,443.780811,432.199447
min,501.000000,2.000000,0.500000,1.000000,256.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.100000,80.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,500.000000
25%,851.750000,16.000000,0.700000,3.000000,1207.500000,6.000000,0.000000,1.000000,0.000000,0.000000,0.0000,0.200000,109.000000,0.000000,9.000000,2.000000,1.000000,5.000000,282.750000,874.750000
50%,1226.000000,32.000000,1.500000,4.000000,2146.500000,11.000000,1.000000,1.000000,1.000000,1.000000,0.0000,0.500000,141.000000,1.000000,12.000000,5.000000,3.000000,10.000000,564.000000,1247.000000
75%,1615.250000,48.000000,2.200000,7.000000,3064.500000,16.000000,1.000000,1.000000,1.000000,1.000000,1.0000,0.800000,170.000000,1.000000,16.000000,9.000000,7.000000,15.000000,947.250000,1633.000000
max,1998.000000,64.000000,3.000000,8.000000,3998.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,200.000000,1.000000,19.000000,18.000000,19.000000,20.000000,1960.000000,1998.000000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BatteryPower    2000 non-null   int64
 1   InternalMemory  2000 non-null   int64
 2   ClockSpeed      2000 non-null   float64
 3   NoOfCores       2000 non-null   int64
 4   RAM             2000 non-null   int64
 5   TalkTime        2000 non-null   int64
 6   DualSim         2000 non-null   int64
 7   3G              2000 non-null   int64
 8   4G              2000 non-null   int64
 9   WiFi            2000 non-null   int64
 10  Bluetooth       2000 non-null   int64
 11  MobileDepth     2000 non-null   float64
 12  MobileWeight    2000 non-null   int64
 13  TouchScreen     2000 non-null   int64
 14  ScreenHeight    2000 non-null   int64
 15  ScreenWidth     2000 non-null   int64
 16  FrontCameraPx   2000 non-null   int64
 17  RearCameraPX    2000 non-null   int64
 18  PxHeight        2000 non-null   int64
 19  PxWeight        2000 non-null   int64
 20  PriceRange      2000 non-null   object
dtypes: float64(2), int64(18), object(1)
memory usage: 328.2+ KB

In [33]:
df.isnull().sum()

BatteryPower      0
InternalMemory    0
ClockSpeed        0
NoOfCores         0
RAM               0
TalkTime          0
DualSim           0
3G                0
4G                0
WiFi              0
Bluetooth         0
MobileDepth       0
MobileWeight      0
TouchScreen       0
ScreenHeight      0
ScreenWidth       0
FrontCameraPx     0
RearCameraPX      0
PxHeight          0
PxWeight          0
PriceRange        0
dtype: int64

In [34]:
print("Duplicate Records:", df.duplicated().sum())

Duplicate Records: 0

In [38]:
features = ["RAM", "BatteryPower", "InternalMemory"]

print(df[features].describe())

               RAM  BatteryPower  InternalMemory
count  2000.000000   2000.000000     2000.000000
mean   2124.213000   1238.518500       32.046500
std    1084.732044    439.418206       18.145715
min     256.000000    501.000000        2.000000
25%    1207.500000    851.750000       16.000000
50%    2146.500000   1226.000000       32.000000
75%    3064.500000   1615.250000       48.000000
max    3998.000000   1998.000000       64.000000

In [39]:
print("="*50)
print("DATASET SUMMARY")
print("="*50)

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

print("\nDescriptive Statistics:")
print(df.describe())

==================================================
DATASET SUMMARY
==================================================

Dataset Shape:
(2000, 21)

Column Names:
['BatteryPower', 'InternalMemory', 'ClockSpeed', 'NoOfCores', 'RAM', 'TalkTime', 'DualSim', '3G', '4G', 'WiFi', 'Bluetooth', 'MobileDepth', 'MobileWeight', 'TouchScreen', 'ScreenHeight', 'ScreenWidth', 'FrontCameraPx', 'RearCameraPX', 'PxHeight', 'PxWeight', 'PriceRange']

Data Types:
BatteryPower        int64
InternalMemory      int64
ClockSpeed        float64
NoOfCores           int64
RAM                 int64
TalkTime            int64
DualSim             int64
3G                  int64
4G                  int64
WiFi                int64
Bluetooth           int64
MobileDepth       float64
MobileWeight        int64
TouchScreen         int64
ScreenHeight        int64
ScreenWidth         int64
FrontCameraPx       int64
RearCameraPX        int64
PxHeight            int64
PxWeight            int64
PriceRange         object
dtype: object

Missing Values:
BatteryPower      0
InternalMemory    0
ClockSpeed        0
NoOfCores         0
RAM               0
TalkTime          0
DualSim           0
3G                0
4G                0
WiFi              0
Bluetooth         0
MobileDepth       0
MobileWeight      0
TouchScreen       0
ScreenHeight      0
ScreenWidth       0
FrontCameraPx     0
RearCameraPX      0
PxHeight          0
PxWeight          0
PriceRange        0
dtype: int64

Duplicate Records:
0

Descriptive Statistics:
       BatteryPower  InternalMemory   ClockSpeed    NoOfCores          RAM  \
count   2000.000000     2000.000000  2000.000000  2000.000000  2000.000000
mean    1238.518500       32.046500     1.522250     4.520500  2124.213000
std      439.418206       18.145715     0.816004     2.287837  1084.732044
min      501.000000        2.000000     0.500000     1.000000   256.000000
25%      851.750000       16.000000     0.700000     3.000000  1207.500000
50%     1226.000000       32.000000     1.500000     4.000000  2146.500000
75%     1615.250000       48.000000     2.200000     7.000000  3064.500000
max     1998.000000       64.000000     3.000000     8.000000  3998.000000

          TalkTime      DualSim           3G           4G         WiFi  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000
mean     11.011000     0.509500     0.761500     0.521500     0.507000
std       5.463955     0.500035     0.426273     0.499662     0.500076
min       2.000000     0.000000     0.000000     0.000000     0.000000
25%       6.000000     0.000000     1.000000     0.000000     0.000000
50%      11.000000     1.000000     1.000000     1.000000     1.000000
75%      16.000000     1.000000     1.000000     1.000000     1.000000
max      20.000000     1.000000     1.000000     1.000000     1.000000

       Bluetooth  MobileDepth  MobileWeight  TouchScreen  ScreenHeight  \
count  2000.0000  2000.000000   2000.000000  2000.000000   2000.000000
mean      0.4950     0.501750    140.249000     0.503000     12.306500
std       0.5001     0.288416     35.399655     0.500116      4.213245
min       0.0000     0.100000     80.000000     0.000000      5.000000
25%       0.0000     0.200000    109.000000     0.000000      9.000000
50%       0.0000     0.500000    141.000000     1.000000     12.000000
75%       1.0000     0.800000    170.000000     1.000000     16.000000
max       1.0000     1.000000    200.000000     1.000000     19.000000

       ScreenWidth  FrontCameraPx  RearCameraPX     PxHeight     PxWeight
count  2000.000000    2000.000000   2000.000000  2000.000000  2000.000000
mean      5.767000       4.309500      9.916500   645.108000  1251.515500
std       4.356398       4.341444      6.064315   443.780811   432.199447
min       0.000000       0.000000      0.000000     0.000000   500.000000
25%       2.000000       1.000000      5.000000   282.750000   874.750000
50%       5.000000       3.000000     10.000000   564.000000  1247.000000
75%       9.000000       7.000000     15.000000   947.250000  1633.000000
max      18.000000      19.000000     20.000000  1960.000000  1998.000000

## Conclusion

- The dataset was successfully loaded and explored.
- The dataset contains no missing values.
- No duplicate records were found.
- The target variable was identified successfully.
- Descriptive statistics were generated for all numerical features.
- The dataset is clean and ready for further analysis.